// DO NOT MODIFY THIS FILE
// YOU DO NOT NEED TO USE OR UNDERSTAND THIS CLASS TO COMPLETE THE ASSIGNMENT.
package factorysim.simulation;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import factorysim.stats.*;

/**
 * Immutable snapshot of simulation statistics.
 * Generated by {@link Simulator} after a run completes.
 * 
 * You do not need to use this class directly. It is only called by the simulator.
 */
public final class Report {

    private static final int MARGIN_WIDTH = 4;

    private final List<MachineStats> machines;
    private final List<BeltStats> belts;
    private final List<SinkEntry> sinkEntries;

    public Report(List<MachineStats> machines, List<BeltStats> belts, 
            List<SinkEntry> sinkEntries) {
        this.machines = List.copyOf(machines);
        this.belts = List.copyOf(belts);
        this.sinkEntries = List.copyOf(sinkEntries);
    }

    /** Returns a copy of the list of all machine reports. */
    public List<MachineStats> getMachineReports() {
        return List.copyOf(machines); 
        // Defensive copy to preserve immutability. MachineStats is immutable.
    }

    /** Returns a copy of the list of all belt reports. */
    public List<BeltStats> getBeltReports() {
        return List.copyOf(belts);
    }

    /** Returns a copy of the list of all sink entries. */
    public List<SinkEntry> getSinkEntries() {
        return List.copyOf(sinkEntries);
    }

    /**
     * Parses a report from its text representation (as produced by {@link #toString()}).
     *
     * This is the inverse of {@code toString()}: it splits each data line on the
     * colon delimiter to extract the name, then parses the value portion.
     * Numeric values may be integers or decimals.
     * 
     * This assumes the String is formatted exactly as produced by {@code toString()}.
     *
     * @param text the report text to parse
     * @return a Report containing the parsed data
     */
    public static Report parse(String text) {
        List<MachineStats> machines = new ArrayList<>();
        List<BeltStats> belts = new ArrayList<>();
        List<SinkEntry> sinkEntries = new ArrayList<>();

        // Extracts the first number after the colon
        Pattern numberPattern = Pattern.compile("\\d+\\.?\\d*");
        // Extracts a parenthesized item type, e.g. "(Ore)"
        Pattern itemTypePattern = Pattern.compile("\\((.+?)\\)");

        String currentSection = null;

        for (String line : text.split("\n")) {
            if (line.isBlank()) {
                continue;
            }

            if (line.contains("=== Machine Utilisation ===")) {
                currentSection = "machine";
            } else if (line.contains("=== Belt Throughput ===")) {
                currentSection = "belt";
            } else if (line.contains("=== Sink ===")) {
                currentSection = "sink";
            } else if (currentSection != null) {
                int colonIndex = line.indexOf(':');
                if (colonIndex < 0) {
                    continue;
                }
                String name = line.substring(0, colonIndex).trim();
                String value = line.substring(colonIndex + 1);

                Matcher numMatcher = numberPattern.matcher(value);
                if (!numMatcher.find()) {
                    continue;
                }
                double number = Double.parseDouble(numMatcher.group());

                switch (currentSection) {
                    case "machine":
                        machines.add(new MachineStats(name, number / 100.0));
                        break;
                    case "belt": {
                        Matcher m = itemTypePattern.matcher(value);
                        String itemType = m.find() ? m.group(1) : "";
                        belts.add(new BeltStats(name, itemType, number));
                        break;
                    }
                    case "sink":
                        sinkEntries.add(new SinkEntry(name, number));
                        break;
                    default:
                        break;
                }
            }
        }

        return new Report(machines, belts, sinkEntries);
    }

    /**
     * Formats the statistics into the report format required for printing.
     */
    @Override
    public String toString() {
        // Compute name and value widths across all sections
        int nameWidth = 0;
        int valueWidth = 0;
        for (MachineStats m : machines) {
            nameWidth = Math.max(nameWidth, m.getName().length());
            valueWidth = Math.max(
                valueWidth,
                String.format("%.1f", m.getUtilisation() * 100.0).length()
            );
        }
        for (BeltStats b : belts) {
            nameWidth = Math.max(nameWidth, b.getName().length());
            valueWidth = Math.max(
                valueWidth,
                String.format("%.1f", b.getItemsPerMinute()).length()
            );
        }
        for (SinkEntry s : sinkEntries) {
            nameWidth = Math.max(nameWidth, s.getItemType().length());
            valueWidth = Math.max(
                valueWidth,
                String.format("%.1f", s.getItemsPerMinute()).length()
            );
        }

        // Margin between name column (plus colon) and value column
        int padWidth = nameWidth + 1 + MARGIN_WIDTH;
        String alignmentFormat = String.format(
            "  %%-%ds%%%d.1f",
            padWidth,
            valueWidth
        );

        StringBuilder sb = new StringBuilder();

        sb.append("=== Machine Utilisation ===\n");
        for (MachineStats m : machines) {
            sb.append(
                String.format(
                    alignmentFormat + "%%\n",
                    m.getName() + ":",
                    m.getUtilisation() * 100.0
                )
            );
        }

        sb.append("\n");
        sb.append("=== Belt Throughput ===\n");
        for (BeltStats b : belts) {
            sb.append(
                String.format(
                    alignmentFormat + " / min (%s)\n",
                    b.getName() + ":",
                    b.getItemsPerMinute(),
                    b.getItemType()
                )
            );
        }

        sb.append("\n");
        sb.append("=== Sink ===\n");
        if (sinkEntries.isEmpty()) {
            sb.append("  (no items consumed)\n");
        } else {
            for (SinkEntry s : sinkEntries) {
                sb.append(
                    String.format(
                        alignmentFormat + " / min\n",
                        s.getItemType() + ":",
                        s.getItemsPerMinute()
                    )
                );
            }
        }

        return sb.toString();
    }
}
